export const clubLogo = {
    'ARS': "https://resources.premierleague.com/premierleague/badges/50/t3@x2.png",
    'AVL': "https://resources.premierleague.com/premierleague/badges/50/t7@x2.png",
    'BOU': "https://resources.premierleague.com/premierleague/badges/50/t91@x2.png",
    'BRE': "https://resources.premierleague.com/premierleague/badges/50/t94@x2.png",
    'BHA': "https://resources.premierleague.com/premierleague/badges/50/t36@x2.png",
    'BUR': "https://resources.premierleague.com/premierleague/badges/50/t90@x2.png",
    'CHE': "https://resources.premierleague.com/premierleague/badges/50/t8@x2.png",
    'CRY': "https://resources.premierleague.com/premierleague/badges/50/t31@x2.png",
    'EVE': "https://resources.premierleague.com/premierleague/badges/50/t11@x2.png",
    'FUL': "https://resources.premierleague.com/premierleague/badges/50/t54@x2.png",
    'LIV': "https://resources.premierleague.com/premierleague/badges/50/t14@x2.png",
    'LUT': "https://resources.premierleague.com/premierleague/badges/50/t102@x2.png",
    'MCI': "https://resources.premierleague.com/premierleague/badges/50/t43@x2.png",
    'MUN': "https://resources.premierleague.com/premierleague/badges/50/t1@x2.png",
    'NEW': "https://resources.premierleague.com/premierleague/badges/50/t4@x2.png",
    'NFO': "https://resources.premierleague.com/premierleague/badges/50/t17@x2.png",
    'SHU': "https://resources.premierleague.com/premierleague/badges/50/t49@x2.png",
    'TOT': "https://resources.premierleague.com/premierleague/badges/50/t6@x2.png",
    'WHU': "https://resources.premierleague.com/premierleague/badges/50/t21@x2.png",
    'WOL': "https://resources.premierleague.com/premierleague/badges/50/t39@x2.png",
}