export const clubLogo = {
    'ARS': require('../assets/club_logos/ARS.png'),
    'AVL': require('../assets/club_logos/AVL.png'),
    'BOU': require('../assets/club_logos/BOU.png'),
    'BRE': require('../assets/club_logos/BRE.png'),
    'BHA': require('../assets/club_logos/BHA.png'),
    'BUR': require('../assets/club_logos/BUR.png'),
    'CHE': require('../assets/club_logos/CHE.png'),
    'CRY': require('../assets/club_logos/CRY.png'),
    'EVE': require('../assets/club_logos/EVE.png'),
    'FUL': require('../assets/club_logos/FUL.png'),
    'LIV': require('../assets/club_logos/LIV.png'),
    'LUT': require('../assets/club_logos/LUT.png'),
    'MCI': require('../assets/club_logos/MCI.png'),
    'MUN': require('../assets/club_logos/MUN.png'),
    'NEW': require('../assets/club_logos/NEW.png'),
    'NFO': require('../assets/club_logos/NFO.png'), 
    'SHU': require('../assets/club_logos/SHU.png'),
    'TOT': require('../assets/club_logos/TOT.png'),
    'WHU': require('../assets/club_logos/WHU.png'),
    'WOL': require('../assets/club_logos/WOL.png'),
}