export const tempData_ClubDetail = [
    {
        name: "Manchester United",
        shortName: "MUN",
        ground: 'Old Trafford',
        city: 'Manchester',
        capacity: '74310',
        founded: '1878',
        pl_titles: '20',
        current_rank: '11',
        manager: 'Erik ten Hag',
        firstKit: 'https://resources.premierleague.com/photos/2023/08/20/25e8c2d0-b14f-4a3b-9e6f-cc8410b906c0/MUN_2324_HK_PL_S1.png?width=260&height=330',
        secondKit: 'https://resources.premierleague.com/photos/2023/08/20/7f6abc6f-07f8-4625-a27d-6565a9a991c4/MUN_2324_AK_PL_S1.png?width=260&height=330',
        thirdKit: 'https://resources.premierleague.com/photos/2023/08/20/04f91325-187c-4e22-8222-a0546e0ece78/MUN_2324_TK_PL_S1.png?width=260&height=330',
        lastMatch_3: {
            date: 'Sun, 20 Aug', 
            home: 'Tottenham',
            homeShortName: 'TOT',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t6@x2.png',
            homeGoal: '2',
            away: 'Man United',
            awayShortName: 'MUN',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '3',
            result: "lose",
        },
        lastMatch_2: {
            date: 'Sun, 26 Aug', 
            home: 'Man United',
            homeShortName: 'MUN',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Nottm Forest',
            awayShortName: 'NFO',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '0',
            result: "win",
        },
        lastMatch_1: {
            date: 'Sun, 26 Aug', 
            home: 'Arsenal',
            homeShortName: 'ARS',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Man United',
            awayShortName: 'MUN',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '1',
            result: "draw",
        },
        nextMatch_1: {
            date: 'Sat, 16 Sep', 
            home: 'Man United',
            homeShortName: 'MUN',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t6@x2.png',
            //homeGoal: '2',
            away: 'Brighton',
            awayShortName: 'BHA',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            //awayGoal: '3',
            // no result
            time: '22:00'
        },
        nextMatch_2: {
            date: 'Sun, 24 Sep', 
            home: 'Burnley',
            homeShortName: 'BUR',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Man United',
            awayShortName: 'MUN',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '0',
            time: '03:00'
        },
        nextMatch_3: {
            date: 'Sat, 30 Sep', 
            home: 'Man United',
            homeShortName: 'MUN',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Crystal Palace',
            awayShortName: 'CRY',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '1',
            time: '22:00'
        },
        general: [
            {'Record (W-D-L)': '2-0-2'},
            {'Goals For': '5'},
            {'Goals Against': '7'},
        ],
        shooting: [
            {'Shots': '5'},
            {'Goals': '64'},
            {'Shots on target': '18'},
            {'Shots on target %': '28.1'},
            {'Goals/Shot': '0.06'},
            {'Goals/Shot on target': '0.22'},
            {'Average Shot Distance': '16.8'},
            {'': ''},
            {'Free kicks': '1'},
            {'Penalty kicks': '1'},
            {'Penalty kicks attempted': '1'},
        ],
        passing: [
            {'Assists': '4'},
            {'': ''},
            {'[Total] Attempted': '2107'},
            {'[Total] Completed': '1735'},
            {'[Total] Completion %': '82.3'},
            {'': ''},
            {'[Short] Attempted': '993'},
            {'[Short] Completed': '892'},
            {'[Short] Completion %': '89.8'},
            {'': ''},
            {'[Medium] Attempted': '740'},
            {'[Medium] Completed': '652'},
            {'[Medium] Completion %': '88.1'},
            {'': ''},
            {'[Long] Attempted': '259'},
            {'[Long] Completed': '141'},
            {'[Long] Completion %': '54.4'},
        ],
        pass_types: [
            {'Live-ball passes': '1929'},
            {'Dead-ball passes': '169'},
            {'Free Kicks': '43'},
            {'Through Balls': '10'},
            {'Switches': '14'},
            {'Crosses': '57'},
            {'Throw-Ins': '61'},
            {'Corner Kicks': '28'},
            {'Offsides': '9'},
            {'Passes blocked': '31'},
        ],
        goal_and_shot_creation: [
            {'Shot Creating Actions': '85'},
            {'[SCA] Live-Ball passes': '119'},
            {'[SCA] Dead-Ball passes': '11'},
            {'[SCA] Take-Ons': '7'},
            {'[SCA] Shots': '7'},
            {'[SCA] Fouls': '5'},
            {'[SCA] Defensive actions': '4'},
            {'': ''},
            {'Goal Creating Actions': '10'},
            {'[GCA] Live-Ball passes': '6'},
            {'[GCA] Dead-Ball passes': '1'},
            {'[GCA] Take-Ons': '1'},
            {'[GCA] Shots': '0'},
            {'[GCA] Fouls': '1'},
            {'[GCA] Defensive actions': '1'},
        ],
        defensive_actions: [
            {'Tackles': '70'},
            {'Tackles Won': '37'},
            {'Tackles in Def 3rd': '33'},
            {'Tackles in Mid 3rd': '29'},
            {'Tackles in Att 3rd': '8'},
            {'': ''},
            {'Challenges': '41'},
            {'Challenges Won': '99'},
            {'': ''},
            {'Blocks': '67'},
            {'Shots blocked': '22'},
            {'Passes blocked': '45'},
            {'': ''},
            {'Interceptions': '31'},
            {'Clearances': '92'},
            {'Errors': '0'},
        ],
        possession: [
            {'Possession': '51.8'},
            {'': ''},
            {'Touches': '2596'},
            {'Touches in Def penalty area': '297'},
            {'Touches in Def 3rd': '829'},
            {'Touches in Mid 3rd': '1067'},
            {'Touches in Att 3rd': '731'},
            {'Touches in Att penalty area': '112'},
            {'': ''},
            {'Take-Ons': '75'},
            {'Take-Ons Success': '32'},
            {'Take-Ons Tackled': '31'},
            {'': ''},
            {'Carries': '1642'},
            {'Total Distance (yards)': '8267'},
            {'Progressive Distance (yards)': '4869'},
            {'Progressive Carries': '97'},
            {'Carries into Att 3rd': '66'},
            {'Carries into Att penalty area': '37'},
            {'Miscontrols': '62'},
            {'Dispossessed': '37'},
            {'': ''},
            {'Passes Received': '1709'},
            {'Progressive Passes Received': '193'},
        ],
        goalkeeping: [
            {'Shot on Target Against': '21'},
            {'Goals Against': '7'},
            {'Saves': '15'},
            {'Save %': '66.7'},
            {'Clean Sheets': '1'},
            {'': ''},
            {'Long Pass Attempted': '37'},
            {'Long Pass Completed': '9'},
            {'Completion %': '24.3'},
            {'': ''},
            {'Passes Attempted': '139'},
            {'Throws Attempted': '15'},
            {'Long Pass %': '23.0'},
            {'Average Pass Length (yards)': '29.6'},
            {'': ''},
            {'Goal Kicks Attempted': '14'},
            {'Long Goal Kick %': '35.7'},
            {'Average GK Length (yards)': '32.9'},
            {'': ''},
            {'Crosses Faced': '63'},
            {'Crosses Stopped': '3'},
            {'': ''},
            {'Actions outside penalty area': '4'},
            {'Average action distance (yards)': '15.8'},
        ],
        miscellaneous: [
            {'Yellow Cards': '12'},
            {'Red Cards': '0'},
            {'Second Yellow Cards': '0'},
            {'Fouls Committed': '43'},
            {'Fouls Drawn': '38'},
            {'': ''},
            {'Penalty Kicks Won': '1'},
            {'Penalty Kicks Conceded': '0'},
            {'Own Goals': '1'},
            {'Ball Recoveries': '230'},
            {'': ''},
            {'Aerial Duels Won': '41'},
            {'Aerial Duels Lost': '54'},
            {'Aerial Duels Won %': '43.2'},
        ],
        players: [
            {
                number: '24',
                name: 'André Onana',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '1',
                name: 'Altay Bayindir',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '22',
                name: 'Tom Heaton',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '29',
                name: 'Aaron Wan-Bissaka',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '6',
                name: 'Lisandro Martínez',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '19',
                name: 'Raphaël Varane',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '20',
                name: 'Diogo Dalot',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '23',
                name: 'Luke Shaw',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '2',
                name: 'Victor Lindelöf',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '5',
                name: 'Harry Maguire',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '35',
                name: 'Jonny Evans',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '12',
                name: 'Tyrell Malacia',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '15',
                name: 'Sergio Reguilón',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '18',
                name: 'Casemiro',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '8',
                name: 'Bruno Fernandes',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '14',
                name: 'Christian Eriksen',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '7',
                name: 'Mason Mount',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '46',
                name: 'Hannibal',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '39',
                name: 'Scott McTominay',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '4',
                name: 'Sofyan Amrabat',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '34',
                name: 'Donny van de Beek',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '37',
                name: 'Kobbie Mainoo',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '47',
                name: 'Shola Shoretire',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '10',
                name: 'Marcus Rashford',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '9',
                name: 'Anthony Martial',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '11',
                name: 'Rasmus Højlund',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '21',
                name: 'Antony',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '17',
                name: 'Alejandro Garnacho',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '25',
                name: 'Jadon Sancho',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '28',
                name: 'Facundo Pellistri',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '16',
                name: 'Amad Diallo',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
        ]
    },
    {
        name: "Manchester City",
        shortName: "MCI",
        ground: 'Etihad Stadium',
        city: 'Manchester',
        capacity: '53400',
        founded: '1887',
        pl_titles: '9',
        current_rank: '1',
        manager: 'Pep Guardiola',
        firstKit: 'https://resources.premierleague.com/photos/2023/08/20/205fc2bd-3bb9-4239-8e49-b87647cb9e0b/MCI_2324_HK_PL_S1.png?width=260&height=330',
        secondKit: 'https://resources.premierleague.com/photos/2023/08/20/b0f8b8bf-7538-41b2-8695-c1cde772f53e/MCI_2324_AK_PL_S1.png?width=260&height=330',
        thirdKit: 'https://resources.premierleague.com/photos/2023/08/20/663ea6d6-3fe9-4852-a0d0-0818fff4a454/MCI_2324_TK_PL_S1.png?width=260&height=330',
        lastMatch_3: {
            date: 'Sun, 20 Aug', 
            home: 'Man City',
            homeShortName: 'MCI',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t6@x2.png',
            homeGoal: '1',
            away: 'Newcastle',
            awayShortName: 'NEW',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '0',
            result: "win",
        },
        lastMatch_2: {
            date: 'Sun, 26 Aug', 
            home: 'Sheff Utd',
            homeShortName: 'SHU',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Man City',
            awayShortName: 'MCI',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '2',
            result: "win",
        },
        lastMatch_1: {
            date: 'Sun, 26 Aug', 
            home: 'Man City',
            homeShortName: 'MCI',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '5',
            away: 'Fulham',
            awayShortName: 'FUL',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '1',
            result: "win",
        },
        nextMatch_1: {
            date: 'Sat, 16 Sep', 
            home: 'West Ham',
            homeShortName: 'WHU',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t6@x2.png',
            //homeGoal: '2',
            away: 'Man City',
            awayShortName: 'MCI',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            //awayGoal: '3',
            // no result
            time: '22:00'
        },
        nextMatch_2: {
            date: 'Sun, 24 Sep', 
            home: 'Man City',
            homeShortName: 'MCI',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Nottm Forest',
            awayShortName: 'NFO',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '0',
            time: '03:00'
        },
        nextMatch_3: {
            date: 'Sat, 30 Sep', 
            home: 'Wolves',
            homeShortName: 'WOL',
            homeLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            homeGoal: '1',
            away: 'Man City',
            awayShortName: 'MCI',
            awayLogo: 'https://resources.premierleague.com/premierleague/badges/50/t1@x2.png',
            awayGoal: '1',
            time: '22:00'
        },
        general: [
            {'Record (W-D-L)': '4-0-0'},
            {'Goals For': '11'},
            {'Goals Against': '2'},
            {'Clean Sheets': '2'},
        ],
        shooting: [
            {'Shots': '11'},
            {'Goals': '66'},
            {'Shots on target': '25'},
            {'Shots on target %': '37.9'},
            {'Goals/Shot': '0.15'},
            {'Goals/Shot on target': '0.40'},
            {'Average Shot Distance': '16.3'},
            {'': ''},
            {'Free kicks': '2'},
            {'Penalty kicks': '1'},
            {'Penalty kicks attempted': '2'},
        ],
        passing: [
            {'Assists': '8'},
            {'': ''},
            {'[Total] Attempted': '3013'},
            {'[Total] Completed': '2675'},
            {'[Total] Completion %': '88.8'},
            {'': ''},
            {'[Short] Attempted': '1360'},
            {'[Short] Completed': '1284'},
            {'[Short] Completion %': '94.4'},
            {'': ''},
            {'[Medium] Attempted': '1203'},
            {'[Medium] Completed': '1100'},
            {'[Medium] Completion %': '91.4'},
            {'': ''},
            {'[Long] Attempted': '313'},
            {'[Long] Completed': '209'},
            {'[Long] Completion %': '66.8'},
        ],
        pass_types: [
            {'Live-ball passes': '2848'},
            {'Dead-ball passes': '160'},
            {'Free Kicks': '45'},
            {'Through Balls': '18'},
            {'Switches': '12'},
            {'Crosses': '66'},
            {'Throw-Ins': '64'},
            {'Corner Kicks': '24'},
            {'Offsides': '5'},
            {'Passes blocked': '31'},
        ],
        goal_and_shot_creation: [
            {'Shot Creating Actions': '127'},
            {'[SCA] Live-Ball passes': '105'},
            {'[SCA] Dead-Ball passes': '6'},
            {'[SCA] Take-Ons': '4'},
            {'[SCA] Shots': '6'},
            {'[SCA] Fouls': '6'},
            {'[SCA] Defensive actions': '0'},
            {'': ''},
            {'Goal Creating Actions': '20'},
            {'[GCA] Live-Ball passes': '14'},
            {'[GCA] Dead-Ball passes': '1'},
            {'[GCA] Take-Ons': '1'},
            {'[GCA] Shots': '3'},
            {'[GCA] Fouls': '1'},
            {'[GCA] Defensive actions': '0'},
        ],
        defensive_actions: [
            {'Tackles': '57'},
            {'Tackles Won': '37'},
            {'Tackles in Def 3rd': '25'},
            {'Tackles in Mid 3rd': '26'},
            {'Tackles in Att 3rd': '6'},
            {'': ''},
            {'Challenges': '47'},
            {'Challenges Won': '29'},
            {'': ''},
            {'Blocks': '30'},
            {'Shots blocked': '6'},
            {'Passes blocked': '24'},
            {'': ''},
            {'Interceptions': '20'},
            {'Clearances': '34'},
            {'Errors': '3'},
        ],
        possession: [
            {'Possession': '67.8'},
            {'': ''},
            {'Touches': '3354'},
            {'Touches in Def penalty area': '244'},
            {'Touches in Def 3rd': '854'},
            {'Touches in Mid 3rd': '1746'},
            {'Touches in Att 3rd': '774'},
            {'Touches in Att penalty area': '117'},
            {'': ''},
            {'Take-Ons': '63'},
            {'Take-Ons Success': '38'},
            {'Take-Ons Tackled': '18'},
            {'': ''},
            {'Carries': '2192'},
            {'Total Distance (yards)': '11600'},
            {'Progressive Distance (yards)': '6220'},
            {'Progressive Carries': '97'},
            {'Carries into Att 3rd': '79'},
            {'Carries into Att penalty area': '25'},
            {'Miscontrols': '42'},
            {'Dispossessed': '26'},
            {'': ''},
            {'Passes Received': '2632'},
            {'Progressive Passes Received': '181'},
        ],
        goalkeeping: [
            {'Shot on Target Against': '7'},
            {'Goals Against': '2'},
            {'Saves': '5'},
            {'Save %': '71.4'},
            {'Clean Sheets': '2'},
            {'': ''},
            {'Long Pass Attempted': '52'},
            {'Long Pass Completed': '24'},
            {'Completion %': '46.2'},
            {'': ''},
            {'Passes Attempted': '182'},
            {'Throws Attempted': '13'},
            {'Long Pass %': '24.7'},
            {'Average Pass Length (yards)': '30.2'},
            {'': ''},
            {'Goal Kicks Attempted': '21'},
            {'Long Goal Kick %': '33.3'},
            {'Average GK Length (yards)': '35.9'},
            {'': ''},
            {'Crosses Faced': '18'},
            {'Crosses Stopped': '2'},
            {'': ''},
            {'Actions outside penalty area': '6'},
            {'Average action distance (yards)': '20.9'},
        ],
        miscellaneous: [
            {'Yellow Cards': '3'},
            {'Red Cards': '0'},
            {'Second Yellow Cards': '0'},
            {'Fouls Committed': '35'},
            {'Fouls Drawn': '42'},
            {'': ''},
            {'Penalty Kicks Won': '1'},
            {'Penalty Kicks Conceded': '0'},
            {'Own Goals': '0'},
            {'Ball Recoveries': '207'},
            {'': ''},
            {'Aerial Duels Won': '36'},
            {'Aerial Duels Lost': '30'},
            {'Aerial Duels Won %': '54.5'},
        ],
        players: [
            {
                number: '24',
                name: 'André Onana',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '1',
                name: 'Altay Bayindir',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '22',
                name: 'Tom Heaton',
                position: 'GK',
                nationality: 'Cameroon',
                age: '27',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/e9c0c1b2_2022.jpg'
            },
            {
                number: '29',
                name: 'Aaron Wan-Bissaka',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '6',
                name: 'Lisandro Martínez',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '19',
                name: 'Raphaël Varane',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '20',
                name: 'Diogo Dalot',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '23',
                name: 'Luke Shaw',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '2',
                name: 'Victor Lindelöf',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '5',
                name: 'Harry Maguire',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '35',
                name: 'Jonny Evans',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '12',
                name: 'Tyrell Malacia',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '15',
                name: 'Sergio Reguilón',
                position: 'DF',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '0',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/9e525177_2022.jpg'
            },
            {
                number: '18',
                name: 'Casemiro',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '8',
                name: 'Bruno Fernandes',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '14',
                name: 'Christian Eriksen',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '7',
                name: 'Mason Mount',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '46',
                name: 'Hannibal',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '39',
                name: 'Scott McTominay',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '4',
                name: 'Sofyan Amrabat',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '34',
                name: 'Donny van de Beek',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '37',
                name: 'Kobbie Mainoo',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '47',
                name: 'Shola Shoretire',
                position: 'MF',
                nationality: 'Brazil',
                age: '31',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '0',
                photo: 'https://fbref.com/req/202302030/images/headshots/4d224fe8_2022.jpg',
            },
            {
                number: '10',
                name: 'Marcus Rashford',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '9',
                name: 'Anthony Martial',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '11',
                name: 'Rasmus Højlund',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '21',
                name: 'Antony',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '17',
                name: 'Alejandro Garnacho',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '25',
                name: 'Jadon Sancho',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '28',
                name: 'Facundo Pellistri',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
            {
                number: '16',
                name: 'Amad Diallo',
                position: 'FW',
                nationality: 'England',
                age: '25',
                footed: 'Right',
                appearances: '4',
                goals: '1',
                assists: '1',
                photo: 'https://fbref.com/req/202302030/images/headshots/a1d5bd30_2022.jpg',
            },
        ]
    },
]
