export const tempData_AW = [
    {
        rank: 1,
        clubName: 'MCI',
        played: 1,
        win: 1,
        draw: 0,
        loss: 0,
        goalDiff: 89,
        points: 103,
    },
    {
        rank: 2,
        clubName: 'TOT',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 7,
        points: 10,
    },
    {
        rank: 3,
        clubName: 'LIV',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 4,
        clubName: 'WHU',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 5,
        clubName: 'ARS',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 6,
        clubName: 'BHA',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 7,
        clubName: 'CRY',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 8,
        clubName: 'BRE',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 9,
        clubName: 'NFO',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 10,
        clubName: 'AVL',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 11,
        clubName: 'MUN',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 12,
        clubName: 'CHE',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 13,
        clubName: 'FUL',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 14,
        clubName: 'NEW',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 15,
        clubName: 'WOL',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 16,
        clubName: 'BOU',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 17,
        clubName: 'SHU',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 18,
        clubName: 'EVE',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 19,
        clubName: 'LUT',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 1,
    },
    {
        rank: 20,
        clubName: 'BUR',
        played: 4,
        win: 3,
        draw: 1,
        loss: 0,
        goalDiff: 6,
        points: 0,
    }
]